;Evolution Text File
;1=Begining of a paragraph, 0=end of text
;2=Alone Sentence
;After a 1 you must specify the delay of that sentence: 
;The range goes 0-256, 70 is 1 second and 0 is no delay
;  '-------------'
db ' WELCOME TO',1,0
db '     A',1,35
DB '  MISTERY',2
db ' PRODUCTION',2
DB 'MAIN CODED BY',1,200
DB '   SARWAZ',2
DB '  GRAFIX BY',1,50
DB '   SUNDAY',2
db '  EVOLUTION',1,50
db '  BBS INTRO',2
db ' ',1,255
DB 'OK LETS BEGIN',0

