; Include File for using Useless Module player


INCLUDE d:\sarwaz\blurmag\player\dos32\OS.INC

INCLUDE d:\sarwaz\blurmag\player\dos32\ERR_CODE.INC

; Loaders
INCLUDE d:\sarwaz\blurmag\player\dos32\XMLOAD.INC
INCLUDE d:\sarwaz\blurmag\player\dos32\MODLOAD.INC


INCLUDE d:\sarwaz\blurmag\player\dos32\USMPLAY.INC
INCLUDE d:\sarwaz\blurmag\player\dos32\USS.INC
INCLUDE d:\sarwaz\blurmag\player\dos32\USSVAR.INC

INCLUDE d:\sarwaz\blurmag\player\dos32\HARDWARE.INC

INCLUDE d:\sarwaz\blurmag\player\dos32\MEMORY.INC
INCLUDE d:\sarwaz\blurmag\player\dos32\UTILS.INC
