;Credits Txt File
;The format is:
; Offset  Long.  DEscription
;  00      2      Coord X
;  02      2      Coord Y
;  04      ?      Text Message
;   n      1      0  Means End Of Sentence, 1 Means End Of Message, 2 =End

;The grid is 80x400

dw  15,100
db  'MISTERY',0
dw  11,150
db  'PRESENTS',1
dw  36,80
db  'A',0
dw  15,130
db  'SPANISH',0
dw  12,180
db 'DIVISION',0
dw  5,230
db 'PRODUCTION',1
dw  17,190
db 'SARWAZ',1
dw  5,190
db 'DARKDESIGN',1
dw  17,190
db 'SUNDAY',1
dw  0,0
db ' ',2 ;Again lame.. :'(




